name: Fetch Hookdeck OpenAPI
on:
  workflow_dispatch: # Manually trigger the workflow
  schedule:
    - cron: "*/15 * * * *"
jobs:
  fetch-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch OpenAPI
        run: | 
          curl https://api.hookdeck.com/2024-03-01/openapi/fern  | jq '.' > openapi.json
      
      - name: Set Git Config
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Check for Changes
        id: git-status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
  
      - name: Create Branch and Commit
        if: steps.git-status.outputs.changed == 'true'
        run: |
          timestamp=$(date +%s)
          branch_name="update-openapi-${timestamp}"
          git checkout -b $branch_name
          git add openapi.json
          git commit -m "Update OpenAPI specification"

      - name: Push Branch
        if: steps.git-status.outputs.changed == 'true'
        run: |
          git push --set-upstream origin "$branch_name"

      - name: Create Pull Request
        if: steps.git-status.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update OpenAPI specification"
          branch: $branch_name
          title: "Update OpenAPI specification"
          body: "This PR updates the OpenAPI specification."
